name: Laravel CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Composer Dependencies
        run: composer install --optimize-autoloader

      - name: Install Node Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Run Laravel Commands
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:cache
          php artisan migrate --force --seed

      - name: Set Directory Permissions
        run: chmod -R 755 storage bootstrap/cache

      - name: Run Unit Tests
        run: php artisan test

      - name: Deploy to UAT Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/staffag_admin/public_html/subdomains/chirper-2025
            git pull origin main
            composer install --no-dev --optimize-autoloader
            npm ci
            npm run build
            php artisan migrate --force --seed
